// Generated by CoffeeScript 1.4.0
(function() {
  var changeSrc, cm, current, getText, keepAlive, lastTime, loadSrc, srcs;

  getText = function($el) {
    var text;
    text = $el.text();
    return text = text.trim();
  };

  srcs = [];

  $(".book-shader").each(function() {
    var $el, src;
    $el = $(this);
    src = getText($el);
    return srcs.push(src);
  });

  $("#shadersrcs").html("");

  require("webcam")();

  require("pages/book")();

  cm = $(".CodeMirror")[0].CodeMirror;

  setInterval(function() {
    return cm.focus();
  }, 1000);

  loadSrc = function(i) {
    var anchor, head, src;
    src = srcs[i];
    anchor = cm.getCursor("anchor");
    head = cm.getCursor("head");
    cm.setValue(src);
    return cm.setSelection(anchor, head);
  };

  current = 0;

  loadSrc(current);

  changeSrc = function(dir) {
    current = current + dir;
    current = (current + srcs.length) % srcs.length;
    return loadSrc(current);
  };

  window.cm = cm;

  $(document).on("keydown", function(e) {
    if (e.keyCode === 112) {
      return changeSrc(-1);
    } else if (e.keyCode === 113) {
      return changeSrc(1);
    }
  });

  lastTime = Date.now();

  keepAlive = function() {
    var diff, time;
    time = Date.now();
    diff = time - lastTime;
    if (diff > 600) {
      loadSrc(current);
    }
    lastTime = Date.now();
    return requestAnimationFrame(keepAlive);
  };

  keepAlive();

}).call(this);
