// Generated by CoffeeScript 1.4.0
(function() {
  var $, _;

  $ = require("jquery");

  _ = require("underscore");

  module.exports = function(opts) {
    var $div, html, htmlify, src, stringify, tree;
    $div = $(opts.div);
    src = opts.src;
    tree = require("parse").parse(src);
    stringify = function(node) {
      if (_.isArray(node)) {
        return _.flatten(node).join("");
      } else {
        return node;
      }
    };
    htmlify = function(node) {
      var s;
      s = "<li><span class='deconstruct-node'>" + (stringify(node)) + "</span>";
      if (_.isArray(node)) {
        s += "<ul>" + (node.filter(_.isArray).map(htmlify).join("")) + "</ul>";
      }
      s += "</li>";
      return s;
    };
    html = "<ul class='deconstruct-tree'>" + (htmlify(tree)) + "</ul>";
    $div.html(html);
    return $div.find(".deconstruct-node").each(function() {
      var $this;
      $this = $(this);
      require("codemirror").runMode($this.text(), "text/x-glsl", this);
      $this.addClass("cm-s-default");
      return $this.css("font-family", "monospace");
    });
  };

}).call(this);
