// Generated by CoffeeScript 1.4.0
(function() {
  var $, ast, _;

  $ = require("jquery");

  _ = require("underscore");

  ast = require("ast");

  module.exports = function(opts) {
    var $div, breakdown, html, htmlify, node, src;
    $div = $(opts.div);
    src = opts.src;
    node = require("parse-glsl").parse(src, "assignment_expression");
    ast.markEnds(node, src.length);
    breakdown = ast.breakdown(node);
    htmlify = function(children) {
      var child, s, _i, _len;
      s = "<ul class='deconstruct-tree'>";
      for (_i = 0, _len = children.length; _i < _len; _i++) {
        child = children[_i];
        s += "<li><span class='deconstruct-node'>" + (ast.stringify(child.node, src)) + "</span>";
        if (child.children.length > 0) {
          s += htmlify(child.children);
        }
        s += "</li>";
      }
      s += "</ul>";
      return s;
    };
    html = htmlify(breakdown);
    $div.html(html);
    return $div.find(".deconstruct-node").each(function() {
      var $this;
      $this = $(this);
      require("codemirror").runMode($this.text(), "text/x-glsl", this);
      $this.addClass("cm-s-default");
      return $this.css("font-family", "monospace");
    });
  };

}).call(this);
