// Generated by CoffeeScript 1.4.0
(function() {
  var $, Emitter, codemirror;

  $ = require("jquery");

  codemirror = require("codemirror");

  Emitter = require('emitter');

  module.exports = function(opts) {
    var $div, cm, editor, errorCheck, multiline, src;
    $div = $(opts.div);
    multiline = opts.multiline || false;
    src = opts.src || "";
    errorCheck = opts.errorCheck || false;
    cm = codemirror($div[0], {
      mode: "text/x-glsl",
      value: src,
      lineNumbers: multiline,
      matchBrackets: true
    });
    if (multiline) {
      cm.setSize("100%", $div.innerHeight());
    } else {
      cm.setSize("100%", cm.defaultTextHeight() + 8);
    }
    editor = {
      codemirror: cm,
      src: function() {
        return src;
      }
    };
    Emitter(editor);
    cm.on("change", function() {
      var error, errors, line, _i, _j, _len, _ref;
      src = cm.getValue();
      if (errorCheck) {
        for (line = _i = 0, _ref = cm.lineCount(); 0 <= _ref ? _i < _ref : _i > _ref; line = 0 <= _ref ? ++_i : --_i) {
          cm.removeLineClass(line, "wrap", "editor-error");
        }
        errors = errorCheck(src);
        if (errors) {
          for (_j = 0, _len = errors.length; _j < _len; _j++) {
            error = errors[_j];
            cm.addLineClass(error.lineNum, "wrap", "editor-error");
          }
          return;
        }
      }
      return editor.emit("change", src);
    });
    return editor;
  };

}).call(this);
